spring:
  application:
    name: runtogether
  config:
    import: db-config.yml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.srltas.runtogether.adapter.out.persistence.mybatis
  type-aliases-package: com.srltas.runtogether.*
