name: Code Style Check

on:
  pull_request:
    branches:
      - main
      - issue_*

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Checkstyle
        run: |
          wget -O checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.18.1/checkstyle-10.18.1-all.jar

      - name: Run Checkstyle
        run: |
          java -DsuppressionFile=codestyle/naver-checkstyle-suppressions.xml -jar checkstyle.jar -c codestyle/naver-checkstyle-rules.xml -f xml -o checkstyle-result.xml src/

      - name: Annotate PR with Checkstyle results
        uses: staabm/annotate-pull-request-from-checkstyle-action@v1
        with:
          files: ./checkstyle-result.xml
